mysite/urls.py
# -*- coding: utf-8 -*-
# обработчик адресов сайта
from django.conf.urls import include, url
from django.contrib import admin

import plan.views
import plan.auth


admin.autodiscover()

urlpatterns = [
    url(r'^workReport/', include('workReport.urls')),
    url(r'^stock/', include('stock.urls')),
    url(r'^constructors/', include('constructors.urls')),
    # панель администратора
    url(r'^admin/', include(admin.site.urls)),
    # выход из сайта
    url(r'^logout/$', plan.auth.logout_view),
    # регистрация на сайте
    url(r'^register/$', plan.auth.register),
    url(r'^register/$', plan.auth.register),
    url(r'^otk/$', include('otk.urls')),
    url(r'^test/', include('myTest.urls')),
    url(r'^', plan.auth.index, name='index'),


]

otk/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from otk.views import reportList

urlpatterns = [
    url(r'^report/list/(?P<area_id>[0-9]+)/$', reportList),


]

stock/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from stock.views import stockBalance, wrExtradition, wrAcceptance, acceptance, providers, index, detailWrExtradition, \
    doWrExtradition, detailWrAcceptance, equipment, stockListAll, detailProvider, createProvider, deleteProvider, \
    createEquipment, deleteEquipment, detailEquipment

urlpatterns = [
    url(r'^stock_balance/(?P<area_id>[0-9]+)/$', stockBalance),
    url(r'^stockListAll/(?P<area_id>[0-9]+)/$', stockListAll),

    url(r'^wrExtradition/(?P<area_id>[0-9]+)/$', wrExtradition),
    url(r'^doWrExtradition/(?P<workReport_id>[0-9]+)/$', doWrExtradition),
    url(r'^wrAcceptance/(?P<area_id>[0-9]+)/$', wrAcceptance),
    url(r'^acceptance/(?P<area_id>[0-9]+)/$', acceptance),
    url(r'^detailWrExtradition/(?P<workReport_id>[0-9]+)/$', detailWrExtradition),
    url(r'^detailWrAcceptance/(?P<workReport_id>[0-9]+)/$', detailWrAcceptance),
    url(r'^detailProvider/(?P<provider_id>[0-9]+)/$', detailProvider),
    url(r'^deleteProvider/(?P<provider_id>[0-9]+)/$', deleteProvider),
    url(r'^providers/$', providers),
    url(r'^createProvider/$', createProvider),

    url(r'^equipment/$', equipment),
    url(r'^createEquipment/$', createEquipment),
    url(r'^deleteEquipment/(?P<equipment_id>[0-9]+)/$', deleteEquipment),
    url(r'^detailEquipment/(?P<equipment_id>[0-9]+)/$', detailEquipment),
    url(r'^', index, name='index'),
]

stock/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

import datetime

from django.db import models

from nop.models import Area


class MoveEquipment(models.Model):
    date = models.DateField(default=datetime.date.today)
    cnt = models.IntegerField(default=0)
    equipment = models.ForeignKey("constructors.Equipment")
    flgAcceptance = models.BooleanField(default=True)
    remainCnt = models.IntegerField(default=0)


    def __str__(self):
        return str(self.equipment) + ":" + str(self.cnt)

    def acceptMoving(self, area_id):
        area = Area.objects.get(pk=area_id)
        ss = self.equipment.stockStruct.get(area=area)
        if self.flgAcceptance:
            ss.cnt += self.cnt
        else:
            ss.cnt -= self.cnt
        ss.save()

# поставщик
class Provider(models.Model):
    # имя
    name = models.TextField(default="", max_length=1000)
    # почта
    mail = models.TextField(default="", max_length=1000)
    # контактное лицо
    contactPerson = models.TextField(default="", max_length=1000)
    # телефон
    tel = models.TextField(default="", max_length=40)
    # комментарий
    comment = models.TextField(default="", max_length=10000)

    def __str__(self):
        return self.name + " (" + self.contactPerson+")"

stock/views.py
# -*- coding: utf-8 -*-
from django.contrib import messages
from django.forms import TextInput
from django.forms.formsets import BaseFormSet, formset_factory
from django.http import HttpResponseRedirect
from django.shortcuts import render

from constructors.form import EquipmentListWithoutSWForm, EquipmentListForm, EquipmentCntWithoutSWForm, \
    EquipmentSingleWithCtnForm, EquipmentConstructorForm, EquipmentConstructorSingleForm, AddEquipmentForm
from constructors.models import Equipment, StockStruct
from plan.forms import LoginForm, subdict
from plan.models import InfoText
from stock.form import StockReadyReportSingleForm, StockLeaveReportSingleForm, StockLeaveReportForm, \
    StockEquipmentListForm, StockEquipmentCntForm, ProviderSingleForm, AddProviderForm, ProviderForm, \
    EquipmentStockSingleForm, EquipmentStockForm, AddStockEquipmentForm
from stock.models import MoveEquipment, Provider
from plan.forms import RequiredFormSet

# главная страница раздела нарядов
from workReport.models import WorkReport


def index(request):
    c = {
        'login_form': LoginForm(),
        'it': InfoText.objects.get(pageName="stock_index"),
        'area_id': Area.objects.first().pk,
    }
    return render(request, "stock/index.html", c)


# баланс на складе
def stockBalance(request, area_id):
    if request.method == "POST":
        # строим форму на основе запроса
        form = EquipmentListForm(request.POST, prefix='main_form')
        # если форма заполнена корректно
        if form.is_valid():
            # получаем объект площадки
            area = Area.objects.get(pk=area_id)
            # формируем список оборудования, у которого есть данные об этой площадке
            lst = []
            for e in form.cleaned_data['equipment']:
                try:
                    eq = Equipment.objects.get(pk=e)
                    flg = True
                    for ss in eq.stockStruct.all():
                        if ss.area == area:
                            lst.append([eq, ss.cnt])
                            flg = False
                    if flg:
                        messages.error(request, "На этой площадке не найдено складской структуры " + eq.name)
                except:
                    messages.error(request, "Оборудования с таким id не найдено")
            # если списокнепустой
            if len(lst) > 0:
                # формируем страницу со списком
                c = {
                    'area_id': int(area_id),  # иначе не сравнить с id площадки при переборе
                    'login_form': LoginForm(),
                    'lst': lst,
                    'areas': Area.objects.all().order_by('name'),
                }
                return render(request, "stock/stockList.html", c)

    c = {
        'area_id': int(area_id),  # иначе не сравнить с id площадки при переборе
        'areas': Area.objects.all().order_by('name'),
        'login_form': LoginForm(),
        'form': EquipmentListWithoutSWForm(prefix="main_form")
    }
    return render(request, "stock/stockBalance.html", c)


def stockListAll(request, area_id):
    lst = []
    area = Area.objects.get(pk=area_id)
    for eq in Equipment.objects.all().exclude(equipmentType=Equipment.TYPE_STANDART_WORK):
        flg = True
        for ss in eq.stockStruct.all():
            if ss.area == area:
                lst.append([eq, ss.cnt])
                flg = False
        if flg:
            messages.error(request, "На этой площадке не найдено складской структуры " + eq.name)
    # формируем страницу со списком
    c = {
        'area_id': int(area_id),  # иначе не сравнить с id площадки при переборе
        'login_form': LoginForm(),
        'lst': lst,
        'areas': Area.objects.all().order_by('name'),
    }
    return render(request, "stock/stockList.html", c)


# Выдача нарядов
def wrExtradition(request, area_id):
    if request.method == 'POST':
        # строим форму на основе запроса
        form = StockReadyReportSingleForm(request.POST)
        # если форма заполнена корректно
        if form.is_valid():
            return HttpResponseRedirect("/stock/detailWrExtradition/" + form.cleaned_data["report"] + "/")

    c = {
        'login_form': LoginForm(),
        'area_id': int(area_id),
        'areas': Area.objects.all().order_by('name'),
        'reportForm': StockReadyReportSingleForm(),
    }
    return render(request, "stock/wrExtradition.html", c)


# выдача по конкретному наряду
def detailWrExtradition(request, workReport_id):
    wr = WorkReport.objects.get(pk=workReport_id)

    if request.method == 'POST':
        # строим форму на основе запроса
        form = StockReadyReportSingleForm(request.POST)
        # если форма заполнена корректно
        if form.is_valid():
            return HttpResponseRedirect("/stock/wrExtradition/" + form.cleaned_data["report"] + "/")

    pE = wr.generateHardwareVals()

    c = {
        'pE': pE,
        'login_form': LoginForm(),
        'area_id': Area.objects.first().pk,
        'areas': Area.objects.all().order_by('name'),
        'reportForm': StockReadyReportSingleForm(),
        'wr': wr,
    }
    return render(request, "stock/detailWrExtradition.html", c)


def doWrExtradition(request, workReport_id):
    wr = WorkReport.objects.get(pk=workReport_id)
    wr.extraditionEquipment()

    return HttpResponseRedirect("/stock/wrExtradition/" + str(Area.objects.first().pk) + "/")


# главная страница раздела нарядов
def wrAcceptance(request, area_id):
    if request.method == 'POST':
        # строим форму на основе запроса
        form = StockLeaveReportSingleForm(request.POST)
        # если форма заполнена корректно
        if form.is_valid():
            return HttpResponseRedirect("/stock/detailWrAcceptance/" + form.cleaned_data["report"] + "/")

    c = {
        'login_form': LoginForm(),
        'area_id': int(area_id),
        'areas': Area.objects.all().order_by('name'),
        'reportForm': StockLeaveReportSingleForm(),
    }
    return render(request, "stock/wrAcceptance.html", c)


# выдача по конкретному наряду
def detailWrAcceptance(request, workReport_id):
    wr = WorkReport.objects.get(pk=workReport_id)
    EquipmentFormset = formset_factory(StockLeaveReportForm)
    if request.method == 'POST':
        equipment_formset = EquipmentFormset(request.POST, request.FILES, prefix='equipment')
        if equipment_formset.is_valid():
            wr.processAcceptanceFormset(equipment_formset, wr.area)
            return HttpResponseRedirect("/stock/wrAcceptance/" + str(wr.area) + "/")

    data = wr.generateAcceptanceData()
    c = {
        'link_formset': EquipmentFormset(initial=data, prefix='equipment'),
        'formset_length': len(data),
        'login_form': LoginForm(),
        'area_id': Area.objects.first().pk,
        'areas': Area.objects.all().order_by('name'),
        'wr': wr,
    }
    return render(request, "stock/detailWrAcceptance.html", c)


# обработать формсет движения оборудования(приёмка/выдача)
def processMovingFomset(formset, flgAcceptance, area_id):
    if formset.is_valid():
        for form in formset.forms:
            try:
                if ("equipment" in form.cleaned_data.keys()) and ("cnt" in form.cleaned_data.keys()):
                    eq = Equipment.objects.get(pk=int(form.cleaned_data["equipment"]))
                    cnt = form.cleaned_data["cnt"]
                    if (cnt is not None):
                        e = MoveEquipment.objects.create(
                            equipment=eq,
                            cnt=cnt,
                            flgAcceptance=flgAcceptance,
                        )
                        e.save()
                        e.acceptMoving(area_id)
            except:
                print("acceptance: ошибка чтения формы")


# приём поставки
def acceptance(request, area_id):
    EquipmentFormset = formset_factory(EquipmentCntWithoutSWForm)
    if request.method == 'POST':
        report_formset = EquipmentFormset(request.POST, request.FILES, prefix="equipment")
        if report_formset.is_valid():
            processMovingFomset(report_formset, True, area_id)

    c = {
        'login_form': LoginForm(),
        'area_id': int(area_id),
        'link_formset': EquipmentFormset(prefix='equipment')
    }
    return render(request, "stock/acceptance.html", c)


# список поставщиков
def providers(request):
    if request.method == "POST":
        # форма редактирования оборудования
        eq_form = ProviderSingleForm(request.POST, prefix='eq_form')
        # если форма заполнена корректно
        if eq_form.is_valid():
            pr = Provider.objects.get(pk=int(eq_form.cleaned_data['provider']))
            return HttpResponseRedirect('/stock/detailProvider/' + str(pr.pk) + '/')
    c = {
        'login_form': LoginForm(),
        'eq_form': ProviderSingleForm(prefix="eq_form"),
        'form': AddProviderForm(prefix="main_form"),
        'area_id': Area.objects.first().pk,
    }
    return render(request, "stock/providers.html", c)


# создать поставщика
def createProvider(request):
    if request.method == "POST":
        # форма редактирования оборудования
        eq_form = AddProviderForm(request.POST, prefix='main_form')
        # если форма заполнена корректно
        if eq_form.is_valid():
            pr = Provider.objects.create(name=eq_form.cleaned_data['name'])
            return HttpResponseRedirect('/stock/detailProvider/' + str(pr.pk) + '/')

    return HttpResponseRedirect('/stock/providers/')


# детализация поставщика
def detailProvider(request, provider_id):
    provider = Provider.objects.get(pk=provider_id)
    if request.method == 'POST':
        provider_form = ProviderForm(request.POST, request.FILES, prefix='equipment')
        if provider_form.is_valid():
            Provider.objects.filter(pk=provider_id).update(**provider_form.cleaned_data)

    c = {'form': ProviderForm(instance=provider, prefix='equipment'),
         'login_form': LoginForm(),

stock/templates/stock/acceptance.html
{% extends "plan/base.html" %}
{% load staticfiles %}
{# Load the tag library #}
{% load bootstrap3 %}
{% load crispy_forms_tags %}
{% load crispy_forms_tags %}
{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}

{% block style_block %}
.centering{
text-align: center;
}
td {
padding: 5px;
}
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.css">
<link rel="stylesheet" type="text/css"
      href="https://cdnjs.cloudflare.com/ajax/libs/select2-bootstrap-css/1.4.6/select2-bootstrap.css">
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.css">
<style>
        #disease{
            width: 50%;  position: relative;top: 220px; left: 182px;
         }

.inactiveLink {
   pointer-events: none;
   cursor: default;
}
</style>
<link rel="stylesheet" type="text/css" href="bootstrap.min.css">
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<link rel="stylesheet" href="/resources/demos/style.css">


<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.css">
<link rel="stylesheet" type="text/css"
      href="https://cdnjs.cloudflare.com/ajax/libs/select2-bootstrap-css/1.4.6/select2-bootstrap.css">
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.css">
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.css">

{% endblock %}

{% block title %}НПО Поиск{% endblock %}


{% block script_block %}

{%  endblock %}


{% block content %}
<h1>Наряды</h1>
{% if user.is_authenticated == False %}
<p>Для доступа к системе Вам надо войти или зарегистрироваться</p>
{% else %}
{% endif %}
{% endblock %}


{% block navigating %}
<a href="/stock/" class="btn btn-default">Главная</a>
<a href="/stock/stock_balance/{{area_id}}/" class="btn btn-default">Баланс на складе</a>
<a href="/stock/wrExtradition/{{area_id}}/" class="btn btn-default">Выдача по наряду</a>
<a href="/stock/wrAcceptance/{{area_id}}/" class="btn btn-default">Приёмка по наряду</a>
<a href="/stock/acceptance/{{area_id}}/" class="btn btn-info">Поставка</a>
<a href="/stock/providers/" class="btn btn-default">Поставщики</a>
<a href="/stock/equipment/" class="btn btn-default">Оборудование</a>
{% endblock %}

{% block sub_content %}

<H3 align="center"> Поставляемое оборудование:</H3>

<form  method="post" class="formset_form">
    {% csrf_token %}

    <br>
    {{ link_formset.management_form }}
    <table cellspacing="3" cellpadding="7" width="40%" align="center">
        <thead>
        <tr>
            <td align="center">Оборудование</td>
            <td align="center">Кол-во</td>
        </tr>
        </thead>
        <tr></tr>
        {% for link_form in link_formset %}
        <tr class="link_formset">
            <td valign="center">{% bootstrap_field link_form.equipment %}</td>
            <td valign="center">{% bootstrap_field link_form.cnt %}</td>
        </tr>
        {% endfor %}
        <div class="placeForAddBtn"></div>
    </table>

    <div align="center">
        <a href="/workReport/equipment/" class="btn btn-default">Назад</a>
        <input align="center" class="btn btn-primary" type="submit" value="Принять" class="button"/>
    </div>
</form>


<script src="https://code.jquery.com/jquery-3.1.1.min.js"
        integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
<script src="{% static '/scripts/formset.centered.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/locale/ru.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.js"></script>
<script>

        $(document).ready(function (){
           $("#disease").select2({
             allowClear:true,
             placeholder: 'Поиск оборудования'
           });
           $("#disease2").select2({
             allowClear:true,
             placeholder: 'Поиск оборудования'
           });
		    $( "#datepicker" ).datepicker({dateFormat: 'yy-mm-dd'});
            $( "#datepicker2" ).datepicker({dateFormat: 'yy-mm-dd'});
            $('.timepicker123').timepicker({
                timeFormat: 'H:mm',
                interval: 15,
                startTime: '10:00',
                dropdown: true,
                scrollbar: true
            });

        })



</script>

<script>
    $('.link_formset').formset({
        addText: 'Добавить',
        deleteText: 'Удалить',
        prefix:'equipment',

    });


</script>


<script type="text/javascript">  $(".js-example-basic-multiple").select2();


</script>


{% endblock %}

{% block error_messages %}
{% endblock %}

stock/templates/stock/detailList.html
equipmentList.html{% extends "plan/base.html" %}
{% load staticfiles %}
{# Load the tag library #}
{% load bootstrap3 %}
{% load crispy_forms_tags %}
{% load crispy_forms_tags %}
{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}

{% block style_block %}
    .centering{
        text-align: center;
    }
    td {
    padding: 5px;
    }
{% endblock %}

{% block title %}НПО Поиск{% endblock %}

{% block content %}
<h1>Склад</h1>
{% if user.is_authenticated == False %}
<p>Для доступа к системе Вам надо войти или зарегистрироваться</p>
{% else %}

{% endif %}
{% endblock %}

{% block navigating %}
<a href="/stock/extradition/{{area_id}}/" class="btn btn-default">Выдача</a>
<a href="/stock/acceptance/{{area_id}}/" class="btn btn-default">Приёмка</a>

<a href="/stock/equipment/list/{{area_id}}/" class="btn btn-default">Оснастка</a>
<a href="/stock/material/list/{{area_id}}/" class="btn btn-default">Материалы</a>
<a href="/stock/detail/list/{{area_id}}/" class="btn btn-info">Детали</a>
<a href="/stock/assembly/list/{{area_id}}/" class="btn btn-default">Сборочные единицы</a>
{% endblock %}

{% block sub_content %}

<br>


<div class="btn-group centering" >
    {% ifnotequal area_id one %}
    <a href="/stock/equipment/list/0/" class="btn btn-info">Красное</a>
    <a href="/stock/equipment/list/1/" class="btn btn-default">Малахит</a>
    {% else %}
    <a href="/stock/equipment/list/0/" class="btn btn-default">Красное</a>
    <a href="/stock/equipment/list/1/" class="btn btn-info">Малахит</a>
    {%endifnotequal%}
</div>
<br>
<form method="post">
     {% csrf_token %}
<table>
    <tr>
        <td> {%  bootstrap_field form.name %}</td>
        <td> {%  bootstrap_field form.dimension %}</td>
    </tr>
</table>

    <input align="center" class="btn btn-primary" type="submit" value="Создать" class="button"/>
</form>

<br>
<br>
<table cellpadding="10" align="center" width="60%">
    {% for eq in eqs%}
    <tr>
        <td>{{ eq.name}}</td>
        <td>{{ eq.cnt}} {{eq.dimension}}</td>
        <td><a href="/stock/equipment/detail/{{ eq.id }}/" class="btn btn-default">Редактировать</a>
        <a href="/stock/equipment/remove/{{ eq.id }}/" class="btn btn-danger">Удалить</a></td>
        <td></td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

{% block error_messages %}
{% endblock %}

stock/templates/stock/detailWrAcceptance.html
{% extends "plan/base.html" %}
{% load staticfiles %}
{# Load the tag library #}
{% load bootstrap3 %}
{% load crispy_forms_tags %}
{% load crispy_forms_tags %}
{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}

{% block style_block %}
.centering{
text-align: center;
}
td {
padding: 5px;
}
#id_equipment-{{formset_length}}-dustCnt{
visibility: hidden;
}
#id_equipment-{{formset_length}}-rejectCnt{
visibility: hidden;
}
#id_equipment-{{formset_length}}-returnCnt{
visibility: hidden;
}
#hidden{
visibility: hidden;
}

<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.css">
<link rel="stylesheet" type="text/css"
      href="https://cdnjs.cloudflare.com/ajax/libs/select2-bootstrap-css/1.4.6/select2-bootstrap.css">
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.css">
<style>
        #disease{
            width: 50%;  position: relative;top: 220px; left: 182px;
         }


</style>
<link rel="stylesheet" type="text/css" href="bootstrap.min.css">
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<link rel="stylesheet" href="/resources/demos/style.css">


<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.css">
<link rel="stylesheet" type="text/css"
      href="https://cdnjs.cloudflare.com/ajax/libs/select2-bootstrap-css/1.4.6/select2-bootstrap.css">
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.css">
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.css">

{% endblock %}

{% block title %}НПО Поиск{% endblock %}

{% block content %}
<h1>Склад</h1>
{% if user.is_authenticated == False %}
<p>Для доступа к системе Вам надо войти или зарегистрироваться</p>
{% else %}

{% endif %}
{% endblock %}

{% block navigating %}
<a href="/stock/" class="btn btn-default">Главная</a>
<a href="/stock/stock_balance/{{area_id}}/" class="btn btn-default">Баланс на складе</a>
<a href="/stock/wrExtradition/{{area_id}}/" class="btn btn-default">Выдача по наряду</a>
<a href="/stock/wrAcceptance/{{area_id}}/" class="btn btn-info">Приёмка по наряду</a>
<a href="/stock/acceptance/{{area_id}}/" class="btn btn-default">Поставка</a>
<a href="/stock/providers/" class="btn btn-default">Поставщики</a>
<a href="/stock/equipment/" class="btn btn-default">Оборудование</a>

{% endblock %}

{% block sub_content %}
<br>

<H3 align="center">Приёмка оборудования по наряду</H3>

<form  method="post" class="formset_form">
    {% csrf_token %}

    {{ link_formset.management_form }}
    <table cellspacing="3" cellpadding="7" width="50%" align="center">
        <thead>
        <tr>
            <td align="left" width="25%"><b>Оборудование</b></td>
            <td align="center" width="20%"><b>Получено</b></td>
            <td align="center"><b>Брак</b></td>
            <td align="center"><b>Утиль</b></td>
            <td align="center"><b>Возвращено</b></td>
        </tr>
        </thead>
        <tr></tr>
        {% for link_form in link_formset %}
        <tr class="link_formset">
            <td align="left">{{ link_form.equipment.value }}<div class="hidden"> {{ link_form.ss }}</div></td>
            <td align="center">{{ link_form.cnt.value }}<div class="hidden"> {{ link_form.cnt }}</div></td>
            <td align="center">{% bootstrap_field link_form.dustCnt %}</td>
            <td align="center">{% bootstrap_field link_form.rejectCnt %}</td>
            <td align="center">{% bootstrap_field link_form.returnCnt %}</td>
        </tr>
        {% endfor %}
    </table>

    <div align="center">
        <a href="/stock/wrAcceptance/{{area_id}}/" class="btn btn-default">Назад </a>
        <input align="center" class="btn btn-primary" type="submit" value="Принять" class="button"/>
    </div>
</form>


<script src="https://code.jquery.com/jquery-3.1.1.min.js"
        integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
<script src="{% static '/scripts/formset.centered.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/locale/ru.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.js"></script>


{% endblock %}

{% block error_messages %}
{% endblock %}